name: Deploy to Firebase Hosting & Functions on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. フロントエンド (Hosting) の依存関係インストールとビルド
      - name: Install & Build Frontend
        run: npm ci && npm run build

      # 2. バックエンド (Functions) の依存関係インストールとビルド
      - name: Install & Build Functions
        run: npm ci && npm run build
        working-directory: ./functions

      # 3. Firebaseへのデプロイ (Hosting と Functions の両方)
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_5070E }}
